### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vitriolix**
updated the readme to make cronet setup more clear

### CODE REVIEW

**Comment by stevenmcdonald** [comment]
Wow, a lot of that stuff is out of date

The build pulls all the dependencies from Maven... documenting where to download and put the aars is only useful for Envoy developers (and also should probably include how you have to modify the build.gradle files to use them if we want to include dev docs)

We use IEnvoyProxy not IPTProxy (I renamed and improved the fork months ago), again it should just pull it from Maven, but the correct link to get the binary would be https://github.com/stevenmcdonald/IEnvoyProxy/releases/tag/e1.2.1

We're currently on cronet 102.0.5005.41 and about to update to 102.0.5005.195 (87.0.4280.66 is what's in the README)

Though I think the use case of not pulling from Maven only applies to those of us working on Envoy too, I'm not generally opposed to documenting things :)

**Comment by mnbogner** [comment]
there might be some overlap with the envoy readme: https://github.com/greatfire/envoy/tree/master/android

**Comment by vitriolix** [comment]
@mnbogner do you want to make those changes in another branch so i can merge this small tweak?

**Comment by mnbogner** [comment]
> @mnbogner do you want to make those changes in another branch so i can merge this small tweak?

I think i just linked that because I thought it might be a useful template.  I do have 2 issues with the changes here:
 - it seems as though all of the step numbers have been changed to 1.
 - i think the envoy/cronet aars should be downloaded from here: https://repo1.maven.org/maven2/org/greatfire/envoy/102.0.5005.195/ and here: https://repo1.maven.org/maven2/org/greatfire/envoy/cronet/102.0.5005.195/ and renamed.

**Comment by vitriolix** [comment]
"it seems as though all of the step numbers have been changed to 1."

in MD you can use all 1. so you can reorder if you want to without renumbering, it renders correctly in increasing numbers

**Comment by stevenmcdonald** [comment]
I'm fine with you merging this, I created an issue to track the need to update the README in the private repo

**Comment by stevenmcdonald** [comment]
@vitriolix I hope you don't find it too presumptuous that I pushed some related updates to this branch, I can back it out and make my own PR if you prefer. 

Most of my updated are removing obsolete information. I removed all the dependency build docs, since that gets pulled from Maven (should we say more about Envoy/Cronet/IEnvoyProxy?), and removed the DNSTT stuff

**Comment by vitriolix** [comment]
np, good place for some docs changes

**Comment by vitriolix** [comment]
feels weird to 🚢 my own pr but 🚢 , if you agree @mnbogner I'll merge it

**Review by mnbogner — APPROVED** [review]

**Comment by mnbogner** [comment]
:+1: :ship:

**Pull request merged**
