### PR TITLE
Upstream merge - December 2022

### PR DESCRIPTION
**Pull request by mnbogner**
There's probably too much here to review, but I can do some more testing and post some screenshots.  The main difference I noticed is that onboarding is now a separate activity which may affect how Envoy is initialized on the first run.

### CODE REVIEW

**Comment by vitriolix** [comment]
Can't really review the change set but maybe you could write up how you are keeping your branch in sync with upstream?  are you just merging upstream into our branch periodically?

**Comment by mnbogner** [comment]
> Can't really review the change set but maybe you could write up how you are keeping your branch in sync with upstream? are you just merging upstream into our branch periodically?

Yes, so far I've been manually merging the upstream commits when we are at a stable point in our own development.

**Comment by vitriolix** [comment]
builds and runs ok for me 🚢

**Review by vitriolix — APPROVED** [review]
builds and runs ok for me 🚢

**Comment by mnbogner** [comment]
I did another round of testing, some screenshots:

 - gf onboarding with user data config on 4th page
ss01

 - home screen
ss02

 - menu showing envoy active
ss03

 - gf preferences with user data config
ss04

 - fdroid onboarding with 3 pages and no user data config
ss05

 - fdroid preferences with no user data config
ss06

I have noticed an occasional issue with startup timing, usually on the first run after a new install, where the envoy broadcast resolves during onboarding and is lost.  This seems to cause the app to use envoy when a direct connection would work, so I don't believe it's worth delaying this merge to address it here.

**Comment by vitriolix** [comment]
is this a regression from the last release?

**Comment by mnbogner** [comment]
> is this a regression from the last release?

I just tested the wiki-unblocked branch and the issue happens there too.  I'm going to go ahead and merge this and work on a fix.

**Pull request merged**
