### PR TITLE
updated fdroid onboarding/preferences

### PR DESCRIPTION
**Pull request by mnbogner**
split onboarding and preference files into extra/fdroid directories to remove user data prompt and logging preferences from fdroid flavor

### CODE REVIEW

**Comment by eighthave** [comment]
FYI, I don't know if there are free software libs to do what you need here.  If there are, then it would be possible to include the analytics stuff in the fdroid build as well.  If the tracking is opt-out, then it would be marked with a `Tracking` anti-feature.  If the tracking is opt-in, it would not be marked.

**Review by eighthave — APPROVED** [review]

**Comment by mnbogner** [comment]
> 

Do you mean free software for analytics in general or for sending analytics to Firebase?  For now it just seemed strange to have the opt-in for a feature that was disabled.

**Comment by eighthave** [comment]
Oh right, the Wikipedia app disables analytics for the fdroid build.  I mean a 
free software lib for submitting to firebase.  If it would be useful, I think it 
would be totally kosher to add opt-in analytics to the fdroid build.

**Comment by vitriolix** [comment]
I agree, if it doesn't get flagged as an anti feature having opt in analytics would be cool

**Comment by mnbogner** [comment]
From my initial search I was able to find open source alternatives to Firebase, but no open source library that could send events to the existing Firebase backend.  I will merge this for now and revisit alternative analytics in the future.

**Comment by eighthave** [comment]
FYI, in case it was not clear, the proprietary library cannot be included in the 
F-Droid.org version. So it could be handled via the `fdroid` build flavor or 
other options.

**Pull request merged**
