### PR TITLE
add fastlane metadata for f-droid

### PR DESCRIPTION
**Pull request by mnbogner**
required for inclusion in f-droid repo

as requested here: https://gitlab.com/fdroid/rfp/-/issues/2197

### CODE REVIEW

**Comment by vitriolix** [comment]
"metadata/zh-Hans/full_description.txt" -Hans ?

**Comment by eighthave** [comment]
"Hans" and "Hant" are the unicode tags for the script, e.g. Han Simplified and 
Han Traditional.

**Comment by eighthave** [comment]
Turns out that Google Play uses country locales rather than script (even though they are less correct): https://support.google.com/googleplay/android-developer/table/4419860

So the _zh-Hans_ folder should be renamed to _zh-CN_.

**Comment by mnbogner** [comment]
based on the check that failed i think the google-services.json files need to be updated to reflect the new package name:
```
> Task :app:dataBindingMergeGenClassesAlphaRelease
* What went wrong:
> Task :app:generateAlphaReleaseResValues
Execution failed for task ':app:processAlphaReleaseGoogleServices'.
> Task :app:generateAlphaReleaseResources
> No matching client found for package name 'org.greatfire.wikiunblocked.alpha'
> Task :app:processAlphaReleaseGoogleServices FAILED
```

**Comment by mnbogner** [comment]
closing this PR in favor of this one created from my repo: https://github.com/greatfire/apps-android-wikipedia-envoy/pull/16

**Pull request closed without merging**
